name: CI

on: 
  push:
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - 'read.me'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - 'read.me'
      - 'README.md'

env:
  TEST_REF_FORBID_GEN_REFS: true

jobs:
  tests-macos11-gpp:
    strategy:
      matrix:
        os: [macos-11]
        compiler: [g++]
        version: [12]
    name: Use ${{ matrix.compiler }}-${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          cd tests
          bash ./run.sh ${{ matrix.compiler }} v${{ matrix.version }}
